[package]
name = "nodepaths"
version = "0.1.0"
authors = ["agreig"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = "3.1.0"
rand_core = "0.6.2"
zeroize = "1.3.0"
